### ISSUE TITLE
Stereo cab sims sound incorrect

### ISSUE THREAD

**Issue by StevenRVE** [AidaDSP/AIDA-X#14]
I compared this Stereo cab sim between the AIDA-X and the IR Loader and they sound very different. It almost sounds like it has a bit of reverb on it when using the AIDA-X cab sim.

IR file:
[1. Guitar Mesa 4x12 V30.zip](https://github.com/AidaDSP/AIDA-X/files/11158558/1.Guitar.Mesa.4x12.V30.zip)

This zip contains a recording of the AIDA-X cab sim and IR loader using the same file
[stereo-cab-sim-comparison.zip](https://github.com/AidaDSP/AIDA-X/files/11158663/stereo-cab-sim-comparison.zip)

AIDA-X info:
- Recorded in Reaper using the AIDA-X vst2
- AMP sim turned off
- All settings unchanged after boot 
![image](https://user-images.githubusercontent.com/42948605/230079704-aca385dd-9b89-4337-87fe-5aafd5d586fa.png)

IR loader info:
- Recorded using the Record-Mono plugin by Brummer
- IR loader Gain: 0.00dB

**Comment by falkTX** [comment]
IR loader you mean the MOD one?

**Comment by StevenRVE** [comment]
Yes, the MOD IR loader

**Comment by falkTX** [comment]
is this for stereo files only? what happens if you make this file mono, is the behaviour still different between the ir loader and aida-x?

**Comment by StevenRVE** [comment]
When I make this file mono the behaviour is the same between the IR loader and the aida-x so this behaviour is for stereo only as far as I can tell. 

I also tested some other stereo IR cab files that I found on this website www.greendog.co.uk/af:
[stereocabirs.zip](https://github.com/AidaDSP/AIDA-X/files/11168451/stereocabirs.zip)
All these files work on the IR loader but make the aida-x crash instantly.

**Comment by falkTX** [comment]
I had some inverted logic, fixed in 1afdddf27b702a57b70af13ce18791ccdf717f3d
Please confirm the fix on the latest build

**Comment by StevenRVE** [comment]
Using this build [5d862e3](https://github.com/AidaDSP/AIDA-X/actions/runs/4681664350), I still get the same issue

**Comment by falkTX** [comment]
this threaded convolver is less stable than I thought..
tested with the greendog IRs, got a crash and adjusted things in 1888cb85545906208b1f5a82a0a0cc00375cfbc8 so it doesnt crash anymore.

Also tried a couple of different IR sizes around the new sync/threaded limit, no crashes so far.
So seems finally fixed to me, please confirm

**Comment by StevenRVE** [comment]
Seems fixed to me as well, closing issue.
